[workspace]
members  = ["atman", "atman-cli"]
resolver = "3"

[workspace.dependencies]
iroh               = "0.90"
serde              = "1"
serde_json         = "1"
thiserror          = "2"
tokio              = "1"
tracing            = "0.1"
tracing-subscriber = "0.3"
