[package]
name = "atman"
version = "0.1.0"
authors = ["Youngjoon Lee"]
edition = "2024"
description = "Atman is a set of protocols that can be embedded into any desktop and mobile applications."
license = "Apache-2.0"
homepage = "https://github.com/atman-project"
repository = "https://github.com/atman-project/atman"
readme = "README.md"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
actman = "0.1"
clap = { version = "4.5.41", features = ["derive"] }
iroh = { version = "0.90", features = ["discovery-local-network"] }
once_cell = "1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
syncman = { git = "https://github.com/atman-project/syncman" }
thiserror = "2"
tokio = { version = "1", features = [
    "macros",
    "sync",
    "time",
    "rt-multi-thread",
] }
tracing = "0.1"
tracing-subscriber = "0.3"
