[package]
authors     = ["Youngjoon Lee"]
description = "Atman is a set of protocols that can be embedded into any desktop and mobile applications."
edition     = "2024"
homepage    = "https://github.com/atman-project"
license     = "Apache-2.0"
name        = "atman"
readme      = "README.md"
repository  = "https://github.com/atman-project/atman"
version     = "0.1.0"

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
actman             = "0.1"
async-trait        = "0.1"
automerge          = "0.6"
autosurgeon        = { version = "0.8", features = ["uuid"] }
iroh               = { workspace = true, features = ["discovery-local-network"] }
once_cell          = "1"
serde              = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true }
syncman            = { git = "https://github.com/atman-project/syncman" }
thiserror          = { workspace = true }
tokio              = { workspace = true, features = ["rt-multi-thread"] }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
uuid               = { version = "1", features = ["v4"] }

[dev-dependencies]
tempdir  = "0.3"
test-log = "0.2"
