name: Binding

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

      - name: Add Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android

      - uses: taiki-e/install-action@cargo-ndk

      - uses: Swatinem/rust-cache@v2

      - name: Build bindings
        run: |
          cd atman
          bash build_bindings.sh --arm64 --sim-arm64 --x86_64 --android --all-features
          cd -
