name: Binding

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios

      - name: Build bindings
        run: |
          cd atman
          bash build_bindings.sh --arm64 --sim-arm64 --x86_64 --all-features
          cd -
