name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --all-features
      - name: Run tests
        run: cargo test --verbose --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Rustfmt
        run: cargo fmt --all --check
      - uses: uncenter/setup-taplo@v1
        if: always()
        with:
          version: "0.9.3"
      - name: Run taplo fmt
        if: always()
        run: taplo fmt --check
      - name: Run taplo lint
        if: always()
        run: taplo lint

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  check-unused-deps:
    name: Check unused deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@v0.9.1

  check-feature-powerset:
    name: Check feature powerset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Check feature powerset
        run: cargo hack check --feature-powerset --no-dev-deps
